// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCna_rfMlE5xbSeQkLrWS0K_fTA0QZfaRQ',
    appId: '1:245070611110:web:564843ea8a98b723a22a67',
    messagingSenderId: '245070611110',
    projectId: 'snake-game-6660c',
    authDomain: 'snake-game-6660c.firebaseapp.com',
    storageBucket: 'snake-game-6660c.appspot.com',
    measurementId: 'G-5BQLKR9F2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJR8wg6JnaTXDEL7bDD6KfzVDiHyfGr9U',
    appId: '1:245070611110:android:fa18516834b17e65a22a67',
    messagingSenderId: '245070611110',
    projectId: 'snake-game-6660c',
    storageBucket: 'snake-game-6660c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEBqWW7o9dHrnVM_uj07tvFWQqXZiAJd4',
    appId: '1:245070611110:ios:44eec7b9f2c8da24a22a67',
    messagingSenderId: '245070611110',
    projectId: 'snake-game-6660c',
    storageBucket: 'snake-game-6660c.appspot.com',
    iosClientId: '245070611110-udtfuaaspap0l9kpmgg8pv3v0uh7k9oe.apps.googleusercontent.com',
    iosBundleId: 'com.snakeGame.snakeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEBqWW7o9dHrnVM_uj07tvFWQqXZiAJd4',
    appId: '1:245070611110:ios:44eec7b9f2c8da24a22a67',
    messagingSenderId: '245070611110',
    projectId: 'snake-game-6660c',
    storageBucket: 'snake-game-6660c.appspot.com',
    iosClientId: '245070611110-udtfuaaspap0l9kpmgg8pv3v0uh7k9oe.apps.googleusercontent.com',
    iosBundleId: 'com.snakeGame.snakeGame',
  );
}
